packages:
  - studio
  - intl
  - web

catalog:
  '@types/react': ^19.3.0
  '@types/react-dom': ^19.3.0
  '@sanity/cli': ^4.22.1
  '@sanity/client': ^7.27.0
  '@sanity/vision': ^4.22.1
  babel-plugin-react-compiler: 19.1.0-rc.3
  react: ^19.3.0
  react-dom: ^19.3.0
  sanity: ^4.22.1
  styled-components: ^6.5.3
  typescript: 5.9.3

overrides:
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  typescript: 'catalog:'

publicHoistPattern:
  - '@sanity/next-loader'
